---
title: "Baby Names Data Interview"
date: "05/22/2023"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
knit: (function(i, encoding) {apstyle::render(i, encoding)})
---
<!-- Timestamp: leave this in to automatically track when a file is rendered -->
*Rendered at `r format(Sys.time(), '%I:%M %p, %b. %d, %Y')`*

<!-- Contact info: leave author/reporter/editor contact info here -->
*Lucas Thomae (<ljthomae@email.unc.edu>)*

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
  )

knitr::opts_knit$set(
  root.dir = rprojroot::find_rstudio_root_file()
  )
```
```{r initialize}
# Load files, environment variables, libraries, etc. here
library(tidyverse)
library(apstyle)
```

```{r}
nationaldf %>%
  filter(year %in% c(1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) %>%
  group_by(year) %>%
  summarise(unique_names = n())
```

```{r}
nationaldf %>%
  filter(sex == "M", year %in% c(1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) %>%
  group_by(year) %>%
  summarise(unique_names = n())
```

```{r}
nationaldf %>%
  filter(sex == "F", year %in% c(1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020)) %>%
  group_by(year) %>%
  summarise(unique_names = n())
```

```{r}
nationaldf %>%
  filter(year==2022, sex=="F") %>%
  arrange(desc(babies))
```

```{r}
nationaldf %>%
  filter(year==2022, sex=="M") %>%
  arrange(desc(babies))
```

```{r}
nationaldf %>%
  filter(name=="Mia", sex=="F")
```

```{r}
nationaldf %>%
  filter(name=="Kobe", sex=="M")
```

```{r}
nationaldf %>%
  filter(name=="Kylian", sex=="M")
```

```{r}
growthdf <-
nationaldf %>%
  filter(year %in% c(2022, 2021, 2018, 2013)) %>%
  pivot_wider(names_from = year, values_from = babies) %>%
  rename('y2022' = '2022', 'y2021' = '2021', 'y2018' = '2018', 'y2013' = '2013') %>%
  mutate(one_year_growth = (y2022-y2021)/y2021*100,
         five_year_growth = (y2022-y2018)/y2018*100,
         ten_year_growth = (y2022-y2013)/y2013*100
         ) %>%
  select(name, sex, y2022, one_year_growth, five_year_growth, ten_year_growth)

growthdf %>%
  arrange(desc(five_year_growth))
```

```{r}
growthdf %>%
  filter(y2022 >= 100) %>%
  arrange(ten_year_growth)
```

```{r}
alexa <-
nationaldf %>%
  filter(name=="Alexa", sex=="F")

alexa %>% filter(year>2012)
```

```{r}
alexaplot <-
ggplot(alexa, aes(x=year, y=babies)) +
  geom_line() +
  scale_x_continuous(
    limits = c(1972, 2022),
    breaks = seq(1972, 2022, 10),
    name = NULL
  ) +
  scale_y_continuous(
    limits = c(0, 6500),
    breaks = seq(0, 6500, 1500),
    name = "Newborn girls named Alexa"
  ) +
  geom_point(data = alexa[alexa$year == 1985, ],
             shape = 21,
             color = "black",
             fill = "black",
             size = 3) +
  annotate("text",
           x = 1981.3,
           y = 755,
           label = "Billy Joel and \n Christie Brinklie name \n daughter Alexa",
           color = "black",
           size = 2.75,
           fontface = "bold") +
  geom_point(data = alexa[alexa$year == 2014, ],
             shape = 21,
             color = "black",
             fill = "lightblue",
             size = 2.5,
             stroke = 1.2) +
  annotate("text",
           x = 2013,
           y = 3500,
           label = "Amazon releases \n Echo and Alexa \n voice service",
           color = "black",
           size = 2.75,
           fontface = "bold") +
  labs(title = "History of the name Alexa in the U.S.",
       subtitle = "The baby name spiked shortly after the Amazon product was launched then sharply declined.",
       caption = "Source: Social Security Administration") +
  theme_ap(family = "") +
  theme(panel.grid.major.x = element_blank(),
        axis.ticks = element_blank())

alexaplot
```

```{r}
isis <-
nationaldf %>%
  filter(name=="Isis", sex=="F")

isis
```

```{r}
isisplot <-
ggplot(isis, aes(x=year, y=babies)) +
  geom_line() +
  scale_x_continuous(
    limits = c(1972, 2022),
    breaks = seq(1972, 2022, 10),
    name = NULL
  ) +
  scale_y_continuous(
    limits = c(0, 600),
    breaks = seq(0, 600, 200),
    name = "Newborn girls named Isis"
  ) +
  geom_point(data = isis[isis$year == 1974, ],
             shape = 21,
             color = "black",
             fill = "black",
             size = 3) +
  annotate("text",
           x = 1978.75,
           y = 0,
           label = "'Isis' rock band \n releases debut album",
           color = "black",
           size = 2.7,
           fontface = "bold") +
  geom_point(data = isis[isis$year == 1975, ],
             shape = 21,
             color = "black",
             fill = "black",
             size = 3) +
  annotate("text",
           x = 1972.7,
           y = 115,
           label = "'Isis' TV \n show debuts \n on CBS",
           color = "black",
           size = 2.7,
           fontface = "bold") +
  geom_rect(xmin = 2014,
            xmax = 2019,
            ymin = -Inf,
            ymax = 515,
            fill = "pink",
            alpha = 0.01) +
  annotate("text",
           x = 2016.5,
           y = 560,
           label = "The reign of \n the Islamic State \n (ISIS) caliphate",
           color = "black",
           size = 2.7,
           fontface = "bold") +
  labs(
    title = "History of the name Isis in the U.S.",
    caption = "Source: Social Security Administration"
  ) +
  theme_ap(family = "") +
  theme(panel.grid.major.x = element_blank(),
        axis.ticks = element_blank())

isisplot
```

```{r}
kobe <-
nationaldf %>%
  filter(name=="Kobe", sex=="M")

kobe
```

```{r}
kobeplot <-
ggplot(kobe, aes(x=year, y=babies)) +
  geom_line(color = "orchid3", size = 1.2) +
  scale_x_continuous(
    limits = c(1995, 2022),
    breaks = seq(1996, 2022, 4),
    name = NULL
  ) +
  scale_y_continuous(
    limits = c(0, 1600),
    breaks = seq(0, 1600, 400),
    name = "Newborn boys named Kobe"
  ) +
  geom_point(data = kobe[kobe$year == 1996, ],
             shape = 21,
             fill = "gold",
             color = "orchid3",
             size = 2,
             stroke = 1.2) +
  annotate("text",
           x = 1999,
           y = 150,
           label = "Kobe Bryant is \n drafted into the NBA",
           color = "black",
           size = 3.25) +
  geom_point(data = kobe[kobe$year == 2000, ],
             shape = 21,
             fill = "gold",
             color = "orchid3",
             size = 2,
             stroke = 1.2) +
  annotate("text",
           x = 1997.3,
           y = 1450,
           label = "Kobe Bryant \n wins his first NBA \n Championship",
           color = "black",
           size = 3.25) +
  geom_point(data = kobe[kobe$year == 2020, ],
             shape = 21,
             fill = "gold",
             color = "orchid3",
             size = 2,
             stroke = 1.2) +
  annotate("text",
           x = 2017,
           y = 1450,
           label = "Kobe Bryant dies in \n a helicopter crash",
           color = "black",
           size = 3.25) +
  labs(title = "History of the name Kobe in the U.S.",
       caption = "Source: Social Security Administration") +
  theme_ap(family = "") +
  theme(panel.grid.major.x = element_blank(),
        axis.ticks = element_blank())

kobeplot
```

<!-- This section is for a tests code block -->

```{r tests}
# Leave this block of code at the end of the file
# If a test fails it will stop the Rmd document from knitting
# Run tests like so:
# source("tests/etl_test.R")
```
